# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb40b04b3712203b5337a46f204665c94315ba93e031538751d18a0b99a6f86f6b3d6e2dfe118b76a0d78627419a576a6e4ebbad1023cafd0a74539c04628be0

test:
  secret_key_base: 125c7299475b93147b95932c5bb345662db420be8650048db1d27efe0468b815f65395f189883c53c368406468d259416e5adc9724f0187217383ce8f3738269

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
